name: GbxExplorer Docker Image push to registry

on:
  push:
    branches: [ "master" ]
    
env:
  BUILD_DIR: Tools/GbxExplorer/Server
  IMAGE_NAME: gbx-explorer
  REGISTRY_URL: ${{ secrets.REGISTRY_URL }}

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build . -f $BUILD_DIR/Dockerfile -t $REGISTRY_URL/$IMAGE_NAME
    - name: Push Docker image to registry
      run: |
        echo ${{ secrets.REGISTRY_PASSWORD }} | docker login $REGISTRY_URL --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin
        docker push $REGISTRY_URL/$IMAGE_NAME
